export enum PlayerPositionEnum {
    "PG" = "Point Guard",
    "SG" = "Shooting Guard",
    "SF" = "Small Forward",
    "PF" = "Power Forward",
    "C" = "Center",
    "QB" = "Quarterback",
    "Q" = "Quarterack",
    "T" = "Tackle",
    "OL" = "Offensive Lineman",
    "WR" = "Wide Receiver",
    "TE" = "Tight End",
    "RB" = "Runningback",
    "G" = "Guard/Goalie",
    "FB" = "Fullback",
    "LB" = "Linebacker",
    "DT" = "Defensive Tackle",
    "CB" = "Cornerback",
    "S" = "Saftey",
    "DB" = "Defensive Back",
    "DE" = "Defensive End",
    "K" = "Kicker",
    "P" = "Punter",
    "LS" = "Long Snapper",
    "LW" = "Left Wing",
    "RW" = "Right Wind",
    "D" = "Defense"
}